; This file was auto-generated by drush make
core = 7.x

api = 2

; Modules
projects[auto_nodetitle][version] = "1.0"

projects[ctools][version] = "1.2"

projects[date][version] = "2.6"

projects[entity][version] = "1.0"

projects[entityreference][version] = "1.0"

projects[features][version] = "1.0"

projects[media][version] = "1.2"

projects[link][version] = "1.0"

projects[location][version] = "3.0-alpha1"

projects[media_soundcloud][version] = "1.0-alpha2"

projects[media_youtube][version] = "2.0-rc1"

projects[pathauto][version] = "1.2"

projects[rules][version] = "2.2"

projects[token][version] = "1.4"

projects[viewfield][version] = "2.0"

projects[views][version] = "3.5"

projects[wysiwyg][version] = "2.2"

