; This file was auto-generated by drush make
core = 7.x

api = 2

; Modules
projects[auto_nodetitle][version] = "1.0"

projects[ctools][version] = "1.2"

projects[colorbox][version] = "2.0+4-dev"

projects[date][version] = "2.6"

projects[devel][version] = "1.3"

projects[entity][version] = "1.0"

projects[entityreference][version] = "1.0"

projects[features][version] = "1.0"

projects[media][version] = "1.2"

projects[libraries][version] = "2.0"

projects[link][version] = "1.0"

projects[location][version] = "3.0-alpha1"

projects[media_soundcloud][version] = "1.0-alpha2"

projects[media_youtube][version] = "2.0-rc1"

projects[omega_tools][version] = "3.0-rc4"

projects[panelizer][version] = "2.0"

projects[panels][version] = "3.3"

projects[pathauto][version] = "1.2"

projects[rules][version] = "2.2"

projects[token][version] = "1.4"

projects[viewfield][version] = "2.0"

projects[views][version] = "3.5"

projects[wysiwyg][version] = "2.2"

; Themes
projects[omega][version] = "3.1"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "http://jacklmoore.com/colorbox/colorbox.zip"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

libraries[profiler][download][type] = "get"
libraries[profiler][download][url] = "http://ftp.drupal.org/files/projects/profiler-7.x-2.0-beta1.tar.gz"

