<?php
/**
 * @file
 * music_festival_components.features.inc
 */

/**
 * Implements hook_views_api().
 */
function music_festival_components_views_api() {
  return array("version" => "3.0");
}

/**
 * Implements hook_node_info().
 */
function music_festival_components_node_info() {
  $items = array(
    'article' => array(
      'name' => t('Article'),
      'base' => 'node_content',
      'description' => t('Use <em>articles</em> for time-sensitive content like news, press releases or blog posts.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'artist' => array(
      'name' => t('Artist'),
      'base' => 'node_content',
      'description' => t('An artist who is performing'),
      'has_title' => '1',
      'title_label' => t('Name'),
      'help' => '',
    ),
    'event' => array(
      'name' => t('Event'),
      'base' => 'node_content',
      'description' => t('A set, event or other occurrence'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'page' => array(
      'name' => t('Basic page'),
      'base' => 'node_content',
      'description' => t('Use <em>basic pages</em> for your static content, such as an \'About us\' page.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}
